export const ingredientList = [
  "Bok Choy",
  "Snake Beans",
  "Sorrel Leaves",
  "Rocket Leaves",
  "Drumstick",
  "Cherry Tomatoes",
  "Kaffir Lime",
  "Plantain",
  "Turnip",
  "Sweet Potatoes",
  "Coriander Powder",
  "Chives",
  "Sage",
  "Rosemary",
  "Flour",
  "Muesli",
  "Oats",
  "Brown Rice",
  "Tapioca",
  "Beef",
  "Grass Fed Chicken",
  "Free Range Chicken",
  "Organic Chicken",
  "Turkey",
  "Skinned Chicken",
  "Pork",
  "Partridge",
  "Ham",
  "Gruyere Cheese",
  "Gouda Cheese",
  "Feta Cheese",
  "Milk",
  "Cranberry",
  "Kiwi",
  "Blueberreis",
  "Mango",
  "Watermelon",
  "Tomato",
  "Strawberry",
  "Canola Oil",
  "Chia Seeds",
  "Hazelnut",
  "Pine Nuts",
  "Mustard Oil",
  "Shrimp",
  "Tuna Fish",
  "Shellfish",
  "Shark",
  "Hilsa",
  "Sardines",
  "Salmon",
  "Prawns",
  "Red Wine",
  "Almond Milk",
  "Brown Sugar",
  "Sugar Candy",
  "Icing Sugar",
  "Honey",
];
