spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: recipe-api-db
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
